# -*- coding: utf-8 -*-
"""FIP_Resizing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18S2MHqEyoZlNnlP1IR-nsjfym53jiziK
"""

import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import numpy as np



img=cv2.imread(r"/content/IT-AIML (2).png",cv2.IMREAD_COLOR)

cv2_imshow(img)

print(img.shape)

width=img.shape[1]#no of columns will lead to width
height=img.shape[0]#no of rows will lead to height

print(f'The width of original image is:{width}\n The height of original image is :{height}')

##Resize the original image
#1. Mention WxH
#a.increase the size
#b.Reduce the size

W=1024
H=1024
New_img=cv2.resize(img,(W,H),interpolation=cv2.INTER_NEAREST)

plt.imshow(New_img)
plt.show()

New_img.shape

print(f'The Width of new image is:{New_img.shape[1]}\n The Height of new image is :{New_img.shape[0]}')

scale=50
W1=int(img.shape[1]*scale/100)
H1=int(img.shape[0]*scale/100)
img1=cv2.resize(img,(W1,H1),interpolation=cv2.INTER_AREA)
plt.imshow(img1)
plt.show()
img1.shape

print(f"The width of the new image:{img1.shape[1]}\nThe Height of the new image:{img1.shape[0]}")

r_img=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)

center=(width/2,height/2)

rotate_matrix=cv2.getRotationMatrix2D(center=center,angle=30,scale=0.67)

rotated_image=cv2.warpAffine(src=img,M=rotate_matrix,dsize=(width,height))

plt.imshow(rotated_image)

r1_img=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
plt.imshow(r1_img)

